### ISSUE TITLE
"Storage Only" Model Type fails in Python

### ISSUE THREAD

**Issue by grgmiller** [RyanCMann/OSESMO#1]
It seems that the "Storage Only" model in python is currently unusable due to a couple of errors:

1) The script is assigning the wrong variable. For example, at line 2047, you assign a "Solar_Only_" variable:
```
if Model_Type_Input == "Storage Only":
    Solar_Only_Peak_Demand_Reduction_Percentage = ""
```
But then at line 2066, you reference a "Solar_Storage_" variable:

```
 if Model_Type_Input == "Storage Only":

        if Solar_Storage_Peak_Demand_Reduction_Percentage >= 0:

            print('Peak demand with storage is {0} kW, representing a DECREASE OF {1}%.'.format(round(Annual_Peak_Demand_with_Solar_and_Storage, 2), round(Solar_Storage_Peak_Demand_Reduction_Percentage, 2)))
```
This is leading to a  "variable referenced before assignment" error

2) Even if the correct variable name is assigned, you are assigning it to the value "", which is interpreted as a string, so that when you try `if Solar_Storage_Peak_Demand_Reduction_Percentage >= 0`, you get `TypeError: '>=' not supported between instances of 'str' and 'int'`

These issues appear to repeat through the end of the code for peak demand, annual energy consumption, and emissions impact calculations.

**Comment by RyanCMann** [comment]
Hi @grgmiller,

Just pushed a commit 738e986 that should resolve the issue. There wasn't anything wrong with the variable names, but the indentation was incorrect. I translated the code from MATLAB, and must not have tested the storage-only case that would have revealed this issue.

I tried running Model_Inputs_Single_Run with the following changes in input variables, and it works fine now.
`Model_Type_Input = "Storage Only"`
`Solar_Profile_Name_Input = "No Solar"`
`Solar_Size_Input = 0`
`ITC_Constraint_Input = 0`

I saw that you forked this repo - are you going to be using this model for your research? Happy to discuss further to help you get started, particularly if you need to make some modifications to the code or input files.

**Comment by grgmiller** [comment]
Thank you! It's working for me now as well. I am hoping to use this for my research. I'll send you an email with more details.
